<?php
/*
Plugin Name: Add Headers
Plugin URI: https://bitbucket.org/gnotaras/wordpress-add-headers
Description: Adds headers to the HTTP responses generated by WordPress.
Version: 1.0.1
Author: George Notaras
Author URI: http://www.g-loaded.eu/
License: GPLv3
*/

/**
 *  This file is part of the Add-Headers distribution package.
 *
 *  Add-Headers is an extension for the WordPress publishing platform.
 *
 *  Homepage:
 *  - http://wordpress.org/plugins/add-headers/
 *  Documentation:
 *  - http://www.codetrax.org/projects/wp-add-headers/wiki
 *  Development Web Site and Bug Tracker:
 *  - http://www.codetrax.org/projects/wp-add-headers
 *  Main Source Code Repository (Mercurial):
 *  - https://bitbucket.org/gnotaras/wordpress-add-headers
 *  Mirror repository (Git):
 *  - https://github.com/gnotaras/wordpress-add-headers
 *
 *  Licensing Information
 *
 *  Copyright 2013 George Notaras <gnot@g-loaded.eu>, CodeTRAX.org
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


// Store plugin directory
define('ADDH_DIR', dirname(__FILE__));

// Import modules
// require_once( join( DIRECTORY_SEPARATOR, array( ADDH_DIR, 'addh-settings.php' ) ) );


/**
 * Translation Domain
 *
 * Translation files are searched in: wp-content/plugins
 */
//load_plugin_textdomain('add-headers', false, dirname( plugin_basename( __FILE__ ) ) . '/languages/');




?>